DROP TABLE IF EXISTS urls CASCADE;
DROP TABLE IF EXISTS url_checks CASCADE;

CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_url PRIMARY KEY (id)
);

CREATE TABLE url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code INT,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description TEXT,
    url_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    foreign key (url_id) references urls(id),
    CONSTRAINT pk_url_check PRIMARY KEY (id)
);
